/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CalendarComponentMonthChange, CalendarComponentOptions, CalendarComponentPayloadTypes, CalendarComponentTypeProperty, CalendarDay, } from "./components/ibiz-mobile-calendar/calendar.model";
export namespace Components {
    interface IbizMobileCalendar {
        "format": string;
        "options": CalendarComponentOptions;
        "readonly": boolean;
        "type": CalendarComponentTypeProperty;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIbizMobileCalendarElement extends Components.IbizMobileCalendar, HTMLStencilElement {
    }
    var HTMLIbizMobileCalendarElement: {
        prototype: HTMLIbizMobileCalendarElement;
        new (): HTMLIbizMobileCalendarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ibiz-mobile-calendar": HTMLIbizMobileCalendarElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IbizMobileCalendar {
        "format"?: string;
        "onChange"?: (event: CustomEvent<CalendarComponentPayloadTypes>) => void;
        "onMonthChange"?: (event: CustomEvent<CalendarComponentMonthChange>) => void;
        "onSelect"?: (event: CustomEvent<CalendarDay>) => void;
        "onSelectEnd"?: (event: CustomEvent<CalendarDay>) => void;
        "onSelectStart"?: (event: CustomEvent<CalendarDay>) => void;
        "options"?: CalendarComponentOptions;
        "readonly"?: boolean;
        "type"?: CalendarComponentTypeProperty;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ibiz-mobile-calendar": IbizMobileCalendar;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ibiz-mobile-calendar": LocalJSX.IbizMobileCalendar & JSXBase.HTMLAttributes<HTMLIbizMobileCalendarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
